layout:
  position: bottom_left
  scale: 1.0
  padding: 20
  mode: landscape
  gap: [24, 360]
  width: 300

appearance:
  corner_radius: 8
  border_width: 2

background:
  style: "smart_transparency"
  opacity: 80

controls:
  show_next_prev: true
